# === Base config
services:
  postgres:
    image: postgres:16.4
    restart: always
    volumes:
      - ./apps/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data

  backend:
    restart: always
    depends_on:
      - postgres

  frontend:
    restart: always
    depends_on:
      - backend
    tmpfs:
      - /tmp

volumes:
  postgres-data:
